services:
  gbalatro:
    image: gbalatro:dev
    build:
      context: .
      dockerfile: Dockerfile.gbalatro
    working_dir: /balatro-gba
    volumes:
      - ./:/balatro-gba
    user: "${UID-1000}:${GID-1000}"
    command: ["sh", "-c", "make -j$(nproc)"]
